from pathlib import Path
import html, json, re
from datetime import datetime, timezone
from email.utils import format_datetime
R=Path(__file__).resolve().parents[1]
e=lambda s:html.escape(str(s),quote=True)
products=json.loads((R/'content/products.json').read_text()); systems=json.loads((R/'content/systems.json').read_text())
articles=sorted([json.loads(p.read_text()) for p in (R/'content/articles').glob('*.json') if json.loads(p.read_text()).get('status')=='published'],key=lambda p:p['date'],reverse=True)
routes=[]
def link(label,url,cls='text-link'):
 return f'<a class="{cls}" href="{e(url)}">{e(label)}</a>'
def button(label,url):
 return f'<a class="button-05" href="{e(url)}"><span class="glass" aria-hidden="true"></span><span class="content"><span class="copy">{e(label)}</span></span></a>'
def brand(p):
 logo=f'<img src="/brand/{e(p["logo"])}" alt="" class="product-logo {"wordmark" if p.get("wordmark") else ""} {p["slug"]}" loading="lazy">' if p.get('logo') else ''
 return f'<span class="product-identity">{logo}<span>{e(p["name"])}</span></span>'
def visual(p):
 return '/editorial/'+p.get('visual','context')+'.jpg'
def product_card(p):
 return f'<a class="product-card" href="/products/{p["slug"]}/" data-category="{e(p["category"])}" data-search="{e(p["name"]+" "+p["tagline"])}"><div class="product-card-image"><img src="{visual(p)}" alt="" loading="lazy" width="1536" height="1024"></div><div class="product-card-head">{brand(p)}</div><div><p class="eyebrow">{e(p["category"])}</p><h3>{e(p["tagline"])}</h3></div></a>'
def image_band(name,caption=''):
 return f'<figure class="image-band"><img src="/editorial/{name}.jpg" alt="" width="1536" height="1024" loading="lazy">{f"<figcaption>{caption}</figcaption>" if caption else ""}</figure>'
def infinite_carousel(items,label='Explore the ecosystem'):
 cards=''
 for duplicate in [False,True]:
  for p in items:
   attrs=' aria-hidden="true"' if duplicate else ''
   cards+=f'<article class="carousel-card" data-carousel-card role="listitem"{attrs}><h2>{e(p["name"])}</h2><div class="carousel-card__media" aria-hidden="true"><img src="{visual(p)}" alt="" draggable="false" loading="lazy"></div><footer class="carousel-card__footer"><p>{e(p["tagline"])}</p><a href="/products/{p["slug"]}/" {"tabindex=-1" if duplicate else ""}>Explore {e(p["name"])}</a></footer></article>'
 return '<div class="carousel-section"><div class="section-heading section"><h2><span data-reveal-06>'+label+'</span></h2><div class="carousel-tools"><span>Drag to explore</span><button type="button" data-carousel-pause aria-pressed="false">Pause motion</button></div></div><section class="infinite-carousel" data-card-carousel data-direction="left" aria-label="'+label+'"><div class="infinite-carousel__track" data-carousel-track role="list">'+cards+'</div></section></div>'
def card_stack():
 items=[('Context','Shared knowledge across tools and sessions.','context'),('Authority','Clear permissions for agents that act.','authority'),('Execution','Reliable environments for useful work.','execution')]
 cards='';captions=''
 for i,(name,copy,img) in enumerate(items):
  active='true' if i==0 else 'false';hidden='false' if i==0 else 'true';state=['active','next','previous'][i]
  cards+=f'<article class="card" data-stack-card data-active="{active}" aria-hidden="{hidden}"><img src="/editorial/{img}.jpg" width="396" height="550" alt="" loading="eager" draggable="false"><span class="stack-card-label" aria-hidden="true">{name}</span></article>'
  captions+=f'<div class="caption" data-stack-caption data-caption-state="{state}" aria-hidden="{hidden}"><h2>{name}</h2><p>{copy}</p></div>'
 return '<div class="stack-showcase"><section data-card-stack role="region" aria-roledescription="carousel" aria-label="Foundations of the ecosystem"><div class="deck" data-stack-deck tabindex="0" aria-label="Card 1 of 3">'+cards+'<div class="drag-proxy" data-stack-drag-proxy aria-hidden="true"></div></div><div class="captions" aria-live="polite">'+captions+'</div></section><div class="stack-controls"><button data-stack-step="-1">Previous</button><span>Drag or use arrow keys</span><button data-stack-step="1">Next</button></div></div>'
def parallax_carousel():
 items=[('Context','Memory that carries forward.','context'),('Authority','Permissions that travel with the work.','authority'),('Execution','From an idea to a useful outcome.','execution'),('Coordination','Focused products, shared foundations.','context'),('Research','Systems for people and agents.','authority')]
 return '<section class="section carousel-intro"><p class="eyebrow">Areas of focus</p><h2><span data-reveal-06>Intelligence in context.</span></h2><div class="carousel-tools"><span>Drag, scroll, or use arrow keys</span><a href="#after-research-carousel">Continue to research</a></div></section><section class="keen-slider" data-parallax-carousel data-lenis-prevent data-drag-speed="0.502" aria-label="Admetos research focus areas" aria-roledescription="carousel" tabindex="0">'+''.join(f'<figure class="card" role="group" aria-roledescription="slide" aria-label="{i+1} of 5"><div class="frame"><div class="media"><img src="/editorial/{img}.jpg" alt="" loading="eager" decoding="async" draggable="false"></div></div><figcaption class="caption"><p class="eyebrow">{name}</p><h3 class="title">{copy}</h3></figcaption></figure>' for i,(name,copy,img) in enumerate(items))+'</section><div id="after-research-carousel"></div>'
def article_card(a):
 return f'<a class="article-card" href="/news/{a["slug"]}/" data-category="{e(a["category"])}"><p class="metadata">{e(a["category"])} <span>{datetime.fromisoformat(a["date"]).strftime("%B %d, %Y")}</span></p><h3>{e(a["title"])}</h3><p>{e(a["excerpt"])}</p></a>'
def intro(label,title,description='',extra=''):
 return f'<header class="page-intro"><p class="eyebrow">{label}</p><h1><span data-reveal-06 data-resting-color="#161616" data-threshold="0.15">{title}</span></h1>{f"<p class=lead>{description}</p>" if description else ""}{extra}</header>'
footer='<footer class="site-footer"><div class="footer-brand"><a class="brand" href="/"><span>Admetos</span></a><p>Research. Products.<br>Possibility.</p></div><div><h2>Products</h2>'+''.join(f'<a href="/products/{p["slug"]}/">{e(p["name"])}</a>' for p in products)+'</div><div><h2>Research</h2><a href="/research/">Our approach</a><a href="/research/hades/">Hades</a><a href="/research/scorpio/">Scorpio</a><a href="/developers/">Developers</a></div><div><h2>Company</h2><a href="/company/">About</a><a href="/news/">News &amp; insights</a><a href="/careers/">Careers</a><a href="/investors/">Investors</a><a href="/contact/">Contact</a><a href="/feed.xml">RSS</a></div><div class="footer-bottom"><span>© 2026 Admetos</span><a href="#top">Back to top</a></div></footer>'
drawer=(R/'references/drawer-markup.html').read_text().split('  <div class="page">')[0]
drawer=re.sub(r'<ul class="links">.*?</ul>', '<ul class="links">'+''.join(f'<li><a href="{url}"><span>{label}</span></a></li>' for label,url in [('Home','/'),('Research','/research/'),('Products','/products/'),('Developers','/developers/'),('News','/news/'),('Company','/company/')])+'</ul>',drawer,flags=re.S)
drawer=re.sub(r'<div class="socials">.*?</div>','<div class="socials"><a href="/contact/">Contact</a><a href="/careers/">Careers</a><a href="/investors/">Investors</a></div>',drawer,flags=re.S)
blur=(R/'references/blur-markup.html').read_text()
aura='<div class="contact-aura" data-aura-border data-dither-src="https://www.details.so/vault-previews/aurora-glow/_astro/dither.DYfTq7JB.png" data-state="off" data-palette="spectrum" aria-hidden="true"><canvas data-aura-canvas></canvas><span data-aura-origin></span></div>'
brandmark='<img src="/brand/admetos-mark.png" width="40" height="40" alt=""><span>Admetos</span>'
footer=footer.replace('<span>Admetos</span>',brandmark)
def write(path,title,description,body,image=None):
 target=R/(path.strip('/')+'/index.html' if path!='/' else 'index.html');target.parent.mkdir(parents=True,exist_ok=True);routes.append(str(target.relative_to(R)))
 doc=f'''<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light"><title>{e(title)} | Admetos</title><meta name="description" content="{e(description)}"><link rel="canonical" href="https://admetos.org{path}"><meta property="og:title" content="{e(title)} | Admetos"><meta property="og:description" content="{e(description)}"><meta property="og:type" content="website"><meta name="twitter:card" content="summary"><link rel="icon" href="/brand/admetos-mark.png"><link rel="alternate" type="application/rss+xml" title="Admetos News" href="/feed.xml"><script type="module" src="/src/main.js"></script></head><body id="top"><a class="skip-link" href="#swup">Skip to content</a>{drawer}<header class="site-header"><a class="brand" href="/" aria-label="Admetos home">{brandmark}</a><nav class="desktop-nav" aria-label="Primary navigation"><a href="/research/">Research</a><a href="/products/">Products</a><a href="/developers/">Developers</a><a href="/news/">News</a><a href="/company/">Company</a></nav></header><div class="page"><div class="page-content"><main id="swup" class="transition-fade">{body}{footer}</main></div>{blur}<button class="cover" type="button" tabindex="-1" aria-label="Close navigation"></button></div></div>{aura}<noscript><style>.hero-section-01 .loader{{display:none}}[data-reveal-06]{{color:#161616;-webkit-text-fill-color:#161616;background:none}}</style></noscript></body></html>'''
 target.write_text('\n'.join(line.rstrip() for line in doc.splitlines())+'\n')
# Home
# Source components keep their original DOM hooks. Only content and light-theme tokens change.
hero=(R/'references/hero-markup.html').read_text()
hero=hero.replace('<main class="hero-page">','<div class="hero-page">').replace('</main>','</div>')
hero=re.sub(r'<header>.*?</header>','',hero,flags=re.S)
hero=re.sub(r'<div class="media".*?</div>\s*</div>\s*<div class="content">','<div class="media" aria-hidden="true"><div class="item active"><video poster="https://images.pexels.com/videos/36244108/pexels-photo-36244108.jpeg?auto=compress&amp;w=1260&amp;h=750&amp;dpr=1" autoplay muted loop playsinline preload="auto"><source src="https://videos.pexels.com/video-files/36244108/15370421_2560_1440_30fps.mp4" type="video/mp4"></video></div></div><div class="content">',hero,flags=re.S)
hero=re.sub(r'<div class="thumbs".*?</div>','<div class="thumbs" hidden inert aria-hidden="true"><button tabindex="-1" aria-label="Hero background video"></button></div>',hero,flags=re.S)
hero=hero.replace('<div class="loader"', '<button class="hero-media-toggle" type="button" data-video-toggle aria-pressed="false">Pause video</button><div class="loader"')
hero=hero.replace('Give your story an unforgettable entrance','Building<br><span data-hero-gradient>tomorrow.<br>Today.</span>')
hero=re.sub(r'(<div class="content">.*?<h1>.*?</h1>)\s*<p>.*?</p>',r'\1<p>Admetos. AI research &amp; development. <span>Intelligent systems. Practical innovation.</span></p>',hero,flags=re.S)
metrics=''.join(f'<div class="metric"><dt><span class="stat-fallback">{value}</span><span class="nf nf-stat" data-number-flow-stat data-start="0" data-value="{value}" aria-label="{value}"><number-flow class="nf-number" data-stat-number></number-flow></span></dt><dd>{label}</dd></div>' for value,label in [(len(products),'Products in the ecosystem'),(len(systems),'Foundational systems'),(4,'Areas of focus')])
home_intro='<section class="section split"><div><p class="eyebrow">AI research laboratory</p><h2>Human ambition.<br><span data-reveal-06 data-resting-color="#161616">Machine intelligence.</span></h2><dl class="metrics">'+metrics+'</dl></div><div class="story-copy"><p class="lead">Admetos builds and operates focused technology companies for AI agents, the people who direct them, and the businesses that rely on them.</p><p>Each product serves a clear customer need. Shared engineering and operating support connect the ecosystem.</p><div class="actions">'+button('Explore our products','/products/')+button('About Admetos','/company/')+'</div></div></section>'
panel_template=re.search(r'<article class="stacked-scroll-panel">.*?</article>',(R/'references/stacked-markup.html').read_text(),re.S).group()
stack_panels=[]
for product in [next(p for p in products if p['slug']==slug) for slug in ['company-os','stored','govern']]:
 panel=re.sub(r'<h2>.*?</h2>','<h2><span>'+product['name']+'</span></h2><p class="project-category">'+product['category']+'</p>',panel_template,flags=re.S)
 panel=re.sub(r'(<div class="stacked-scroll-panel__description">)\s*<p>.*?</p>',lambda m:m[1]+'<p>'+product['description']+'</p>'+button('Explore '+product['name'],'/products/'+product['slug']+'/'),panel,flags=re.S)
 panel=re.sub(r'<img\s+.*?/>',lambda m:f'<img class="stacked-scroll-panel__image" src="{visual(product)}" alt="" loading="lazy">',panel,flags=re.S)
 stack_panels.append(panel)
stack='<div class="stacked-scroll-preview" data-theme="light"><section class="stacked-scroll-panels" data-stacked-scroll-panels aria-label="Featured Admetos products">'+''.join(stack_panels)+'</section></div>'
rest='<section class="section"><div class="section-heading"><h2>The ecosystem.</h2>'+link('All products','/products/')+'</div><div class="product-grid">'+''.join(product_card(p) for p in products)+'</div></section><section class="section split"><p class="eyebrow">Research</p><div><h2>Context. Authority.<br>Execution. Coordination.</h2><p class="lead">We study the foundations that turn intelligence into dependable work.</p><div class="actions">'+button('Inside the lab','/research/')+'</div></div></section><section class="section"><div class="section-heading"><h2>From the lab.</h2>'+link('News & insights','/news/')+'</div><div class="news-home">'+''.join(article_card(a) for a in articles)+'<div class="journal-note"><p class="eyebrow">News & insights</p><p>Articles, product updates, research notes, and ideas from across Admetos.</p>'+link('Follow via RSS','/feed.xml')+'</div></div></section>'
home=hero.replace('<!-- Existing or new next-section content -->',home_intro+infinite_carousel(products[:7])+stack+rest)
write('/','Research & Products', 'Admetos is an independent technology lab building software for people, AI agents, and the companies they run together.', home)
filters='<div class="filters" role="group" aria-label="Filter products">'+''.join(f'<button data-filter="{x}" aria-pressed="{"true" if x=="All" else "false"}">{x}</button>' for x in ['All','Workspaces','Infrastructure','Applications'])+'</div>'
productbody=intro('Products','The Admetos ecosystem.','Independent products. A shared ambition to expand what people and agents can do.')+'<section class="section catalog" data-filter-scope><div class="catalog-controls">'+filters+'<label class="search-label">Find a product<input type="search" placeholder="Search products" data-search-input></label></div><p class="result-count" aria-live="polite" data-result-count>11 products</p><div class="product-grid">'+''.join(product_card(p) for p in products)+'</div><p class="empty-state" data-empty hidden>No products match. Try another search or category.</p></section><section class="section statement"><h2>Start with what you need.</h2><p>Each product has its own purpose. Explore its site for current features, availability, and access. Adopting the entire ecosystem is never the starting requirement.</p></section>'
write('/products/','Products','Explore Stored, Govern, Cadre, Company OS, Chippi, Scalar, TellMe, Operate, Marketer, Symbolic, and Clusters.',productbody)
for p in products:
 product_visual=f'<div class="product-brand-stage"><img class="product-detail-art" src="{visual(p)}" alt="" width="1536" height="1024"><div class="brand-caption">{brand(p)}</div></div>'
 body=intro(p['category'],p['name'],p['tagline'],f'<div class="actions">{button("Visit "+p["name"],p["url"])}{link("All products","/products/")}</div>')+f'<section class="product-detail section">{product_visual}<div><p class="eyebrow">About {e(p["name"])}</p><h2>{e(p["tagline"])}</h2><p class="lead">{e(p["description"])}</p><ul class="capabilities">'+''.join(f'<li>{e(x)}</li>' for x in p['capabilities'])+'</ul></div></section><section class="section related"><div class="section-heading"><h2>Explore the ecosystem</h2>'+link('All products','/products/')+'</div><div class="product-grid">'+''.join(product_card(x) for x in products if x['slug']!=p['slug'])[:0]+'</div></section>'
 # Related products are chosen from the same category, falling back to the ecosystem.
 related=[x for x in products if x['slug']!=p['slug'] and x['category']==p['category']][:3]
 body=body.replace('<div class="product-grid"></div>','<div class="product-grid">'+''.join(product_card(x) for x in related)+'</div>')
 write('/products/'+p['slug']+'/',p['name'],p['description'],body)
focus=[('Context','Make knowledge available across tools and sessions.','Stored'),('Authority','Define what an agent can do, and keep a record of its actions.','Govern'),('Execution','Give agents a reliable place to use tools and complete work.','Hades · Cadre'),('Coordination','Carry goals and state across teams, products, and time.','Company OS · Operate · Scorpio')]
research=intro('Research','Intelligence needs<br>an environment.','Our work explores the infrastructure around AI: how agents remember, act, coordinate, and remain accountable.')+'<section class="section research-disciplines"><h2>Areas of focus</h2><div class="accordion">'+''.join(f'<article class="item"><input class="toggle" type="checkbox" id="focus-{i}"><label class="question" for="focus-{i}"><span>{n}</span><span class="icon" aria-hidden="true"><span class="icon-mark"></span></span></label><div class="answer"><div class="answer-inner"><p>{d}</p><p>{p}</p></div></div></article>' for i,(n,d,p) in enumerate(focus))+'</div></section><section class="section"><div class="section-heading"><h2>Foundational systems</h2><p>Foundational work from the Admetos lab.</p></div><div class="system-grid">'+''.join(f'<a class="system-card" href="/research/{s["slug"]}/"><p class="eyebrow">{s["role"]}</p><h3>{s["name"]}</h3><p>{s["description"]}</p></a>' for s in systems)+'</div></section>'
research=research.replace('<section class="section research-disciplines">',parallax_carousel()+'<section class="section research-disciplines">')
write('/research/','Research', 'Explore Admetos research in context, authority, execution, and coordination for AI agents.',research)
for s in systems:
 body=intro('Research / '+s['role'],s['name'],s['description'])+image_band('execution' if s['slug']=='hades' else 'authority')+f'<section class="section reading"><p class="eyebrow">Areas of work</p><h2>{s["role"]}</h2><ul class="capabilities">'+''.join(f'<li>{e(x)}</li>' for x in s['capabilities'])+'</ul><p>Explore the research direction and contact Admetos to discuss the work. This page describes the system’s focus; it is not a claim of a public product release.</p>'+link('Research inquiries','mailto:hello@admetos.org?subject=Research%20inquiry')+'</section>'
 write('/research/'+s['slug']+'/',s['name'],s['description'],body)
company=intro('Company','A lab for what<br>comes next.','Admetos builds and operates focused technology companies for AI agents, the people who direct them, and the businesses that rely on them.')+'<section class="section split"><p class="eyebrow">Our purpose</p><div><h2>Make intelligence<br>useful in the world.</h2><p class="lead">A capable model is only the beginning. Agents need memory, permissions, reliable execution, and a way to coordinate work over time. We build the products around those needs.</p></div></section><section class="section focus-grid">'+''.join(f'<article><span class="index">0{i+1}</span><h3>{n}</h3><p>{d}</p></article>' for i,(n,d) in enumerate([('Start with a real problem','Every product begins with a clear customer need.'),('Keep products independent','A customer can use one product without adopting the full ecosystem.'),('Build for lasting value','Reliability, clear authority, and thoughtful design are part of the work.')]))+'</section><section class="section split"><p class="eyebrow">How we operate</p><div><h2>Focused companies.<br>Shared foundations.</h2><p class="lead">Admetos provides shared engineering, operating support, and direction. Each product keeps its own purpose and customers.</p><div class="actions">'+link('Careers','/careers/')+link('Investor information','/investors/')+'</div></div></section>'
company=company.replace('<section class="section focus-grid">', '<section class="section company-foundations"><div><p class="eyebrow">Shared foundations</p><h2><span data-reveal-06>Independent products.<br>A connected ecosystem.</span></h2><p class="lead">Memory, authority, and execution form the foundations of the work.</p></div>'+card_stack()+'</section><section class="section focus-grid">')
write('/company/','Company','Meet Admetos: independent research and focused products for people and AI agents.',company)
developers=intro('Developers','Build with the ecosystem.','Choose the product that fits your work, then use its own documentation to connect your tools and agents.')+'<section class="section"><div class="focus-grid"><article><p class="eyebrow">Context</p><h2>Stored</h2><p>Connect shared organizational memory through MCP or API.</p>'+link('Explore Stored','https://www.stored.to')+'</article><article><p class="eyebrow">Authority</p><h2>Govern</h2><p>Add identity, permissions, and action records to agent workflows.</p>'+link('Explore Govern','https://www.govern.sh')+'</article><article><p class="eyebrow">Capabilities</p><h2>Clusters</h2><p>Discover skills, agents, tools, prompts, and loops.</p>'+link('Explore Clusters','https://www.clusters.to')+'</article></div></section><section class="section statement"><h2>Work with the lab.</h2><p>For questions about the ecosystem, system architecture, or collaboration, get in touch.</p>'+button('Contact Admetos','/contact/')+'</section>'
developers=developers.replace('<section class="section statement">',infinite_carousel([p for p in products if p['category']=='Infrastructure'],'Build with these foundations')+'<section class="section statement">')
write('/developers/','Developers','Find Admetos products for shared context, agent authority, capabilities, and execution.',developers)
news=intro('News & insights','From the lab.','Articles, product updates, research notes, and ideas from across Admetos.')+'<section class="section" data-filter-scope><div class="filters" role="group" aria-label="Filter news">'+''.join(f'<button data-filter="{c}" aria-pressed="{"true" if c=="All" else "false"}">{c}</button>' for c in ['All','Company','Research','Product updates','Engineering'])+'</div><div class="news-grid">'+''.join(article_card(a) for a in articles)+'</div><p class="empty-state" data-empty>No articles in this category yet. Explore all articles or follow the RSS feed for future updates.</p><div class="section-end">'+link('Follow via RSS','/feed.xml')+'</div></section>'
news=news.replace('<section class="section" data-filter-scope>', image_band('context')+'<section class="section" data-filter-scope>')
write('/news/','News & insights','Articles, updates, and research notes from Admetos.',news)
for a in articles:
 date=datetime.fromisoformat(a['date']).strftime('%B %d, %Y')
 body=f'<article class="editorial"><header><a class="eyebrow" href="/news/">News / {e(a["category"])}</a><h1><span data-reveal-06 data-resting-color="#161616">{e(a["title"])}</span></h1><p class="lead">{e(a["excerpt"])}</p><p class="metadata">{date} <span>By {e(a["author"])}</span></p></header><div class="article-body">'+''.join(f'<section><h2>{e(s["heading"])}</h2>'+''.join(f'<p>{e(p)}</p>' for p in s['paragraphs'])+'</section>' for s in a['sections'])+'</div><div class="article-end">'+link('Back to news','/news/')+'</div></article>'
 write('/news/'+a['slug']+'/',a['title'],a['excerpt'],body)
careers=intro('Careers','Build something<br>worth working on.','We value clear thinking, thoughtful execution, and products that help people do more.')+'<section class="section reading"><h2>Areas of work</h2><p>Applied systems, product engineering, infrastructure and security, design, and company building.</p><p>There are no open roles listed here yet. You can still introduce yourself and share what you want to build.</p>'+button('Introduce yourself','mailto:hello@admetos.org?subject=Careers%20at%20Admetos')+'</section>'
careers=careers.replace('<section class="section reading">',image_band('execution')+'<section class="section reading">')
write('/careers/','Careers','Explore work at Admetos in applied systems, engineering, design, and company building.',careers)
investors=intro('Investors','A long view<br>of intelligent systems.','Admetos builds focused software companies around the infrastructure and applications agents need.')+'<section class="section reading"><h2>Independent products.<br>Shared operating support.</h2><p>Our approach combines focused customer needs with shared engineering and company-building resources. We care about useful products, dependable systems, and lasting value.</p><p>For information about the company and its operating model, contact Admetos directly.</p>'+button('Investor inquiries','mailto:hello@admetos.org?subject=Investor%20inquiry')+'</section>'
investors=investors.replace('<section class="section reading">',image_band('authority')+'<section class="section reading">')
write('/investors/','Investors','The strategy and operating model behind the Admetos ecosystem.',investors)
contact=intro('Contact','Let’s work on<br>what comes next.','For research, product, partnership, or company inquiries, contact Admetos.')+'<section class="section contact-grid"><div><p class="eyebrow">Get in touch</p><h2><a href="mailto:hello@admetos.org">hello@admetos.org</a></h2></div><div><p class="eyebrow">Explore</p>'+link('Products','/products/')+link('Careers','/careers/')+link('Investors','/investors/')+'</div></section>'
contact=contact.replace('<section class="section contact-grid">',image_band('context')+'<section class="section contact-grid">')
write('/contact/','Contact','Get in touch with Admetos.',contact)
# Keep previously published routes useful; canonical redirects configured at the host.
for path,title,body in [('/projects/','Products',productbody),('/portfolio/','Products',productbody),('/lab/','Research',research),('/mission/','Company',company),('/systems/','Research',research)]:write(path,title,title+' at Admetos.',body)
(R/'content/routes.json').write_text(json.dumps(routes,indent=2))
(R/'public/sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>https://admetos.org/'+p.replace('index.html','')+'</loc></url>' for p in routes)+'</urlset>')
(R/'public/robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: https://admetos.org/sitemap.xml\n')
(R/'public/feed.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Admetos News</title><link>https://admetos.org/news/</link><description>Articles and updates from Admetos.</description>'+''.join(f'<item><title>{e(a["title"])}</title><link>https://admetos.org/news/{a["slug"]}/</link><guid>https://admetos.org/news/{a["slug"]}/</guid><description>{e(a["excerpt"])}</description><pubDate>{format_datetime(datetime.fromisoformat(a["date"]).replace(tzinfo=timezone.utc))}</pubDate></item>' for a in articles)+'</channel></rss>')
print(f'Generated {len(routes)} pages, {len(products)} products, {len(articles)} published articles. Drafts excluded.')
